### ISSUE TITLE
url validator rejects localhost

### ISSUE THREAD

**Issue by yokotaso** [kintone/plugin-manifest-validator#175]
## Background
When developing a kintone plugin or kintone customize uploader,
I want to develop with webpack-dev-server or VSCode Live Server.

## Problem
But `https://localhost:8080` will be rejected.
On kintone UI, url accepts url like a https://localhost:8080 is acceptable setting.

## Workaround
I modify /etc/hosts (in linux, or macOS). and set a url like `kintone.dev.local`.
and use above url as a webpack-dev-server public url.

There are a little technical and complicated. So, I want to modify to permit localhost.

**Comment by zaki-yama** [comment]
@yokotaso 
We fixed the problem and published new version `2.0.9`.
Thank you!
